{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "universal.fullname" . }}
  namespace: {{ include "universal.namespace" . }}
  labels:
    {{- include "universal.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "universal.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas | default .Values.replicaCount }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.metrics }}
  {{ .Values.autoscaling.metrics | indent 4 }}
  {{- else }}
  {{- if .Values.autoscaling.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.cpu }}
  {{- end }}
  {{- if .Values.autoscaling.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.autoscaling.memory }}
  {{- end }}
  {{- if .Values.autoscaling.requests }}
  - type: Pods
    pods:
      metric:
        name: http_requests
      target:
        type: AverageValue
        averageValue: {{ .Values.autoscaling.requests }}
  {{- end }}
  {{- end }}
{{- end }}
