dependencies:
  - name: rancher-pushprox
    alias: rkeControllerManager
    version: 0.1.2
    repository: https://ekristen.github.io/helm-charts
    condition: rkeControllerManager.enabled

  - name: rancher-pushprox
    alias: rkeScheduler
    version: 0.1.2
    repository: https://ekristen.github.io/helm-charts
    condition: rkeScheduler.enabled

  - name: rancher-pushprox
    alias: rkeProxy
    version: 0.1.2
    repository: https://ekristen.github.io/helm-charts
    condition: rkeProxy.enabled

  - name: rancher-pushprox
    alias: rkeEtcd
    version: 0.1.2
    repository: https://ekristen.github.io/helm-charts
    condition: rkeEtcd.enabled
