## k3s PushProx Monitoring
## ref: https://github.com/rancher/charts/tree/master/packages/rancher-pushprox
##
k3sServer:
  enabled: true
  metricsPort: 10249
  component: k3s-server
  # customLabels:
  #   pushprox: k3s
  # customAnnotations:
  #   service: monitoring
  clients:
    port: 10013
    useLocalhost: true
    tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"

k3sControllerManager:
  enabled: true
  metricsPort: 10252
  component: kube-controller-manager
  # customLabels:
  #   pushprox: k3s
  # customAnnotations:
  #   service: monitoring
  clients:
    port: 10011
    useLocalhost: true
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
    tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"

k3sScheduler:
  enabled: true
  metricsPort: 10251
  component: kube-scheduler
  # customLabels:
  #   pushprox: k3s
  # customAnnotations:
  #   service: monitoring
  clients:
    port: 10012
    useLocalhost: true
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
    tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"

ks3Proxy:
  enabled: true
  metricsPort: 10249
  component: kube-proxy
  # customLabels:
  #   pushprox: k3s
  # customAnnotations:
  #   service: monitoring
  clients:
    port: 10013
    useLocalhost: true
    tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"

# Disabled by default because k3s defaults to sqlite instead of etcd
k3sEtcd:
  enabled: false
  metricsPort: 2381
  component: kube-etcd
  # customLabels:
  #   pushprox: k3s
  # customAnnotations:
  #   service: monitoring
  clients:
    port: 10014
    https:
      enabled: true
      certDir: /etc/kubernetes/ssl
      certFile: kube-etcd-*.pem
      keyFile: kube-etcd-*-key.pem
      caCertFile: kube-ca.pem
    nodeSelector:
      node-role.kubernetes.io/master: "true"
    tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"
