{{- if and .Values.proxy }}{{ if .Values.proxy.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pushProxy.proxy.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "pushProxy.proxy.labels" . | nindent 4 }}
{{- end }}{{- end }}
