apiVersion: v1
appVersion: 1.29.2
deprecated: true
description: |
  Simply Envoy chart for Kubernetes
home: https://www.envoyproxy.io/
icon: https://avatars0.githubusercontent.com/u/30125649
keywords:
  - envoy
  - proxy
name: envoy
sources:
  - https://github.com/envoyproxy/envoy
version: 1.12.0
