service:
  enabled: true
  ports:
    - name: metrics
      port: 9797
      targetPort: 9797
    - name: http
      port: 9898
      targetPort: 9898
    - name: external
      port: 9898
      targetPort: 9898
    - name: grpc
      port: 9999
      targetService: podinfo
