dependencies:
  - name: rancher-pushprox
    alias: rke2ControllerManager
    version: 0.1.2
    repository: https://ekristen.github.io/helm-charts
    condition: rke2ControllerManager.enabled

  - name: rancher-pushprox
    alias: rke2Scheduler
    version: 0.1.2
    repository: https://ekristen.github.io/helm-charts
    condition: rke2Scheduler.enabled

  - name: rancher-pushprox
    alias: rke2Proxy
    version: 0.1.2
    repository: https://ekristen.github.io/helm-charts
    condition: rke2Proxy.enabled

  - name: rancher-pushprox
    alias: rke2Etcd
    version: 0.1.2
    repository: https://ekristen.github.io/helm-charts
    condition: rke2Etcd.enabled