## rke2 PushProx Monitoring
## ref: https://github.com/rancher/charts/tree/master/packages/rancher-pushprox
##
rke2ControllerManager:
  enabled: true
  metricsPort: 10252
  component: kube-controller-manager
  clients:
    port: 10011
    useLocalhost: true
    nodeSelector:
      node-role.kubernetes.io/master: "true"
    tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"

rke2Scheduler:
  enabled: true
  metricsPort: 10251
  component: kube-scheduler
  clients:
    port: 10012
    useLocalhost: true
    nodeSelector:
      node-role.kubernetes.io/master: "true"
    tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"

rke2Proxy:
  enabled: true
  metricsPort: 10249
  component: kube-proxy
  clients:
    port: 10013
    useLocalhost: true
  tolerations:
    - effect: "NoExecute"
      operator: "Exists"
    - effect: "NoSchedule"
      operator: "Exists"

rke2Etcd:
  enabled: true
  metricsPort: 2381
  component: kube-etcd
  clients:
    port: 10014
    useLocalhost: true
    nodeSelector:
      node-role.kubernetes.io/etcd: "true"
    tolerations:
      - effect: "NoSchedule"
        key: node-role.kubernetes.io/master
        operator: "Equal"
